In [183]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import losses as lo_ss
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense, Dropout
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.preprocessing import StandardScaler
import seaborn as sns
from sklearn import model_selection

In [184]:
import os
github_raw_link="https://raw.githubusercontent.com/Aryansh085/LAP/main/858417d1-7d54-4115-a01b-fdda5e03ada3_testing_combined_rows4035_disc_1_0p9_MULTIPLY_preproces_155cols.csv"
df=pd.read_csv((github_raw_link),header = None)

df

,0,1,2,3,4,5,6,7,8,9,...,145,146,147,148,149,150,151,152,153,154
0,2,0.000027,-18.8,1.0,-51.2,5928.833355,796.358239,-2237.601612,-4291.285903,485.614457,...,-184.665696,-143.541755,-356.073963,-155.953441,-571.260816,548.824942,-147.125237,-15.699306,-114.852994,-125.048631
1,0,0.000030,-18.8,1.0,-51.2,-861.308727,2307.828939,1422.328418,-2551.334533,-561.570173,...,270.453742,-52.096877,195.996829,-103.884779,111.627671,19.870049,209.325186,13.936288,261.752370,15.264500
2,0,0.000034,-18.7,1.0,-50.6,-1851.188870,-1823.489706,-1483.762355,956.114350,-2017.286057,...,193.869011,94.069003,-126.387084,145.724626,131.659001,-84.659240,90.034459,-63.858855,-79.851765,-36.496837
3,0,0.000038,-18.5,1.0,-50.0,3826.693181,3614.186279,-1810.579042,-228.922261,-270.595184,...,-174.377444,-143.659035,-24.409795,3.847896,-80.058108,-12.424300,-2.449475,-82.492338,33.375895,10.991025
4,0,0.000042,-18.4,1.0,-49.4,-2345.665781,-1009.244748,-2798.268228,87.699940,326.821614,...,64.504130,-210.224006,-65.296202,40.269294,24.559670,-71.945851,103.014317,-113.017795,145.268924,-112.158828
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4030,2,0.000000,82.9,31.8,-61.4,-1245.734872,-1615.032049,-1784.158416,361.415756,156.039717,...,-3.633283,-99.510990,52.122663,-141.796568,168.401590,-145.657905,78.278022,38.090024,-214.492314,145.345199
4031,2,0.000000,82.7,31.8,-61.4,1743.167881,-219.969994,353.010067,413.369952,-1057.733851,...,-371.606440,-161.391936,90.013115,56.553212,17.573522,136.672030,145.804752,-203.689696,-118.373036,52.921203
4032,0,0.000000,82.5,31.8,-61.3,7523.643927,-1346.518049,-437.245974,-3184.785512,697.115396,...,-87.525202,-60.850698,211.654447,-121.017454,443.020185,-395.819706,-85.330893,-357.307181,-178.380422,75.121322
4033,2,0.000000,82.5,31.8,-61.4,-1639.431817,3837.660828,-218.350574,2473.661181,0.514134,...,79.065958,-12.731323,-97.202328,-74.081315,-277.071732,50.313883,-6.449069,-194.796294,-248.021765,-117.951381
4034,2,0.000000,82.5,31.8,-61.4,-1687.918422,-1416.745916,1508.833009,-3202.899478,479.292536,...,56.731513,52.588404,-62.325078,-236.009245,256.691281,72.667507,405.343475,-174.863390,158.616327,23.589513

In [185]:
df.shape

(4035, 155)

In [186]:
df.dropna()

,0,1,2,3,4,5,6,7,8,9,...,145,146,147,148,149,150,151,152,153,154
0,2,0.000027,-18.8,1.0,-51.2,5928.833355,796.358239,-2237.601612,-4291.285903,485.614457,...,-184.665696,-143.541755,-356.073963,-155.953441,-571.260816,548.824942,-147.125237,-15.699306,-114.852994,-125.048631
1,0,0.000030,-18.8,1.0,-51.2,-861.308727,2307.828939,1422.328418,-2551.334533,-561.570173,...,270.453742,-52.096877,195.996829,-103.884779,111.627671,19.870049,209.325186,13.936288,261.752370,15.264500
2,0,0.000034,-18.7,1.0,-50.6,-1851.188870,-1823.489706,-1483.762355,956.114350,-2017.286057,...,193.869011,94.069003,-126.387084,145.724626,131.659001,-84.659240,90.034459,-63.858855,-79.851765,-36.496837
3,0,0.000038,-18.5,1.0,-50.0,3826.693181,3614.186279,-1810.579042,-228.922261,-270.595184,...,-174.377444,-143.659035,-24.409795,3.847896,-80.058108,-12.424300,-2.449475,-82.492338,33.375895,10.991025
4,0,0.000042,-18.4,1.0,-49.4,-2345.665781,-1009.244748,-2798.268228,87.699940,326.821614,...,64.504130,-210.224006,-65.296202,40.269294,24.559670,-71.945851,103.014317,-113.017795,145.268924,-112.158828
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4030,2,0.000000,82.9,31.8,-61.4,-1245.734872,-1615.032049,-1784.158416,361.415756,156.039717,...,-3.633283,-99.510990,52.122663,-141.796568,168.401590,-145.657905,78.278022,38.090024,-214.492314,145.345199
4031,2,0.000000,82.7,31.8,-61.4,1743.167881,-219.969994,353.010067,413.369952,-1057.733851,...,-371.606440,-161.391936,90.013115,56.553212,17.573522,136.672030,145.804752,-203.689696,-118.373036,52.921203
4032,0,0.000000,82.5,31.8,-61.3,7523.643927,-1346.518049,-437.245974,-3184.785512,697.115396,...,-87.525202,-60.850698,211.654447,-121.017454,443.020185,-395.819706,-85.330893,-357.307181,-178.380422,75.121322
4033,2,0.000000,82.5,31.8,-61.4,-1639.431817,3837.660828,-218.350574,2473.661181,0.514134,...,79.065958,-12.731323,-97.202328,-74.081315,-277.071732,50.313883,-6.449069,-194.796294,-248.021765,-117.951381
4034,2,0.000000,82.5,31.8,-61.4,-1687.918422,-1416.745916,1508.833009,-3202.899478,479.292536,...,56.731513,52.588404,-62.325078,-236.009245,256.691281,72.667507,405.343475,-174.863390,158.616327,23.589513

In [187]:
df.shape

(4035, 155)

In [188]:
y=np.array(df[0])

In [189]:
y.shape

(4035,)

In [190]:
x=np.array([df[i] for i in range(5,155)])
print(x.T.shape)

(4035, 150)

In [191]:
x_train,x_test,y_train,y_test=model_selection.train_test_split(x.T,y)

In [192]:
y_train.shape

(3026,)

In [193]:
from sklearn.preprocessing import StandardScaler

In [194]:
slr=StandardScaler()
slr.fit(x_train)
x_train = slr.transform(x_train)
x_test = slr.transform(x_test)
print(y_train.shape)
y_train=tf.keras.utils.to_categorical(y_train)
y_test=tf.keras.utils.to_categorical(y_test)

(3026,)

In [200]:
model=Sequential()
model.add(Dense(128,input_shape=(150,)))
model.add(Dropout(0.2))
model.add(Dense(64,activation="relu"))
model.add(Dropout(0.2))
model.add(Dense(3))

In [201]:
print(set(y))
print(y_train.shape)
x_train.shape,y_train.shape,x_test.shape,y_test.shape

{0, 1, 2}
(3026, 3)

((3026, 150), (3026, 3), (1009, 150), (1009, 3))

In [202]:
model.compile(loss='mean_squared_error', optimizer='adam')

In [203]:
model.fit(x_train, y_train, epochs=4, batch_size = 1)

Epoch 1/4
3026/3026 [==============================] - 7s 2ms/step - loss: 0.5374
Epoch 2/4
3026/3026 [==============================] - 6s 2ms/step - loss: 0.2324
Epoch 3/4
3026/3026 [==============================] - 6s 2ms/step - loss: 0.2214
Epoch 4/4
3026/3026 [==============================] - 6s 2ms/step - loss: 0.2184

In [215]:
model.evaluate(x_train,y_train)

95/95 [==============================] - 0s 3ms/step - loss: 0.2007

0.20067600905895233

In [205]:
model.evaluate(x_test,y_test)

32/32 [==============================] - 0s 2ms/step - loss: 0.2253

0.22530654072761536

In [206]:
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((3026, 150), (3026, 3), (1009, 150), (1009, 3))

In [207]:
y_pre=model.predict(x_test)

32/32 [==============================] - 0s 1ms/step

In [208]:
print(y_pre.shape)

(1009, 3)

In [209]:
y_pre_ans=np.array([np.argmax(i)  for i in y_pre])

In [210]:
print(set(y_pre_ans))

{0, 1, 2}

In [211]:
y_test_ans=np.array([np.argmax(i)  for i in y_test])

In [212]:
from sklearn.metrics import confusion_matrix

In [213]:
print(confusion_matrix(y_test_ans,y_pre_ans))

[[395   1  57]
 [223   0  44]
 [250   0  39]]